.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitsend_qt test_bitsend_qt
clean: FORCE
	$(MAKE) -C .. bitsend_qt_clean test_bitsend_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitsend_qt_check
bitsend-qt bitsend-qt.exe: FORCE
	 $(MAKE) -C .. bitsend_qt
